import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import BackImage from "./backgroundImage.png"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{backgroundImage:`url(${BackImage.src})`,backgroundSize:"cover",backgroundRepeat:"no-repeat",backgroundAttachment:"fixed"}}>{children}</body>
    </html>
  )
}
